// <auto-generated />
using Bulky_razor_App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky_razor_App.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bulky_razor_App.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryOrder = 1,
                            Name = "Cat 1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryOrder = 2,
                            Name = "Cat 2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryOrder = 3,
                            Name = "Cat 3"
                        },
                        new
                        {
                            Id = 4,
                            CategoryOrder = 4,
                            Name = "Cat 4"
                        },
                        new
                        {
                            Id = 5,
                            CategoryOrder = 5,
                            Name = "Cat 5"
                        },
                        new
                        {
                            Id = 6,
                            CategoryOrder = 6,
                            Name = "Cat 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
